#!/usr/bin/env python3
"""Regenerate automations/README.md from automations/catalog.yaml.

The catalog is the single source of truth. This script renders the human-facing
index from it so the two can never drift. `scripts/validate.py` re-runs this in
memory and fails if the committed README does not match.

    python3 scripts/build_automation_index.py          # write
    python3 scripts/build_automation_index.py --check   # exit 1 if stale
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent / "lib"))
from miniyaml import load_file  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
CATALOG = ROOT / "automations" / "catalog.yaml"
INDEX = ROOT / "automations" / "README.md"

CATEGORIES = [
    ("daily-leadership", "Daily leadership", "Running the day instead of reacting to it."),
    ("pipeline", "Pipeline", "Finding the files that are quietly going wrong."),
    ("coaching", "Loan Officer coaching", "Preparing, running, and documenting coaching."),
    ("meetings", "Team meetings", "Agendas that teach, and action items that survive."),
    ("recruiting", "Recruiting", "Keeping the candidate pipeline warm before you need it."),
    ("partners", "Referral partners", "Noticing decay early and bringing real value."),
    ("training", "Training", "Training the gap that costs production."),
    ("marketing", "Marketing", "Staying visible without inventing content every week."),
    ("executive", "Executive workflows", "Reviewing yourself, not only everyone else."),
    ("ai-workflows", "AI workflows", "Finding leverage and building it safely."),
]

HEADER = """# Automation library

{count} automations across {ncat} categories. Every one ships **inactive**.

## How to actually use these

Most of them need no setup at all. Open [`catalog.yaml`](catalog.yaml), find the one you
want, and copy its `prompt` into a conversation with your agent. That is it. The `trigger`
field is a suggestion for when to run it, not something that runs on its own.

When you are ready to put one on a real schedule, read
[`../docs/automation-safety.md`](../docs/automation-safety.md) first. The short version:

> the agent prepares → you review → you approve → the system executes

Nothing in this library sends a message, changes a record, or publishes anything on its own.

To add your own, follow [`schema.md`](schema.md), then run:

```bash
python3 scripts/build_automation_index.py && python3 scripts/validate.py
```

---
"""

FOOTER = """
---

## Field reference

Every card declares: `id`, `name`, `category`, `objective`, `trigger`, `cadence`,
`data_needed`, `skill`, `prompt`, `output`, `approval_required`, `privacy`, `setup`,
`customization`, `active`, and `time_saved_per_month`. See [`schema.md`](schema.md).

<!-- Generated by scripts/build_automation_index.py — edit catalog.yaml, not this file. -->
"""


def render() -> str:
    catalog = load_file(CATALOG)
    items = catalog["automations"]
    by_cat = {}
    for item in items:
        by_cat.setdefault(item["category"], []).append(item)

    unknown = set(by_cat) - {c[0] for c in CATEGORIES}
    if unknown:
        raise SystemExit(f"catalog.yaml uses unknown categories: {sorted(unknown)}")

    parts = [HEADER.format(count=len(items), ncat=len(CATEGORIES))]
    for key, title, blurb in CATEGORIES:
        rows = by_cat.get(key, [])
        parts.append(f"\n## {title}\n\n{blurb}\n")
        parts.append("| Automation | What it does | Cadence | Needs approval |")
        parts.append("|---|---|---|---|")
        for item in rows:
            approval = "yes" if item["approval_required"] else "no"
            parts.append(
                f"| `{item['id']}` | {item['objective']} | {item['cadence']} | {approval} |"
            )
        parts.append("")
    parts.append(FOOTER)
    return "\n".join(parts).replace("\n\n\n", "\n\n")


def main() -> int:
    rendered = render()
    if "--check" in sys.argv:
        current = INDEX.read_text(encoding="utf-8") if INDEX.exists() else ""
        if current != rendered:
            print("automations/README.md is out of date. Run:")
            print("  python3 scripts/build_automation_index.py")
            return 1
        print("automations/README.md is in sync with catalog.yaml")
        return 0
    INDEX.write_text(rendered, encoding="utf-8")
    print(f"wrote {INDEX.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
